//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexitech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IntentName { get; set; }
        public string RequestBody { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string ResponseBody { get; set; }
    
        public virtual User User { get; set; }
    }
}
